# Generated by Django 3.2.20 on 2023-09-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_madre', models.CharField(max_length=255)),
                ('carnet_identidad_madre', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(max_length=500)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=255, null=True)),
                ('provincia', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnostico_ingreso', models.CharField(max_length=1000)),
                ('atresia_esofagica', models.BooleanField(default=False)),
                ('defectos_pared', models.BooleanField(default=False)),
                ('atresia_estemos_intestinales', models.BooleanField(default=False)),
                ('defectos_diafragmaticos', models.BooleanField(default=False)),
                ('otros', models.BooleanField(default=False)),
                ('resultado_alta', models.CharField(max_length=255)),
                ('embarazada_de_riesgo', models.CharField(blank=True, max_length=255, null=True)),
                ('comprobacion_consejo_genetico', models.CharField(blank=True, max_length=255, null=True)),
                ('captacion_precoz', models.BooleanField(default=False)),
                ('num_controles_embarazo', models.IntegerField(default=0)),
                ('diagnostico_prenatal', models.BooleanField(default=False)),
                ('hoja_contrarreferencia', models.BooleanField(default=False)),
                ('prog_acciones', models.BooleanField(default=False)),
                ('cronograma_seguimiento', models.BooleanField(default=False)),
                ('info_maternidad', models.BooleanField(default=False)),
                ('coordinacion_equipos_ginecologia', models.BooleanField(default=False)),
                ('criterio_cirujano', models.CharField(blank=True, max_length=255, null=True)),
                ('neonatologo_salon_parto', models.BooleanField(default=None)),
                ('actuacion_segun_afeccion', models.BooleanField(default=None)),
                ('ginecologo_asignado', models.BooleanField(default=None)),
                ('coordinacion_traslado', models.BooleanField(default=None)),
                ('coincidencia_diagnostica', models.BooleanField(default=False)),
                ('coordinacion_trasado', models.BooleanField(default=False)),
                ('justificacion_traslado', models.BooleanField(default=False)),
                ('evaluacion_traslado', models.CharField(blank=True, max_length=255, null=True)),
                ('deficiencias_traslado', models.CharField(blank=True, max_length=1000, null=True)),
                ('interconsulta_cirujano', models.BooleanField(default=None)),
            ],
        ),
    ]
