# Generated by Django 3.2.20 on 2023-09-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_auto_20230908_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='coordinacion_trasado',
            new_name='coordinacion_trasado_cerecine',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='coordinacion_traslado',
            new_name='coordinacion_traslado_provincial',
        ),
        migrations.AddField(
            model_name='paciente',
            name='prog_acciones_caso_individual',
            field=models.BooleanField(default=False),
        ),
    ]
