# Generated by Django 3.2.20 on 2023-09-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_auto_20230909_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='atresia_esofagica',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='atresia_estemos_intestinales',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='captacion_precoz',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='defectos_diafragmaticos',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='defectos_pared',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='otros',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
