# Generated by Django 3.2.20 on 2023-09-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_auto_20230909_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='coincidencia_diagnostica',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='confirmacion_segunda_opinion',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='coordinacion_equipos_ginecologia',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='coordinacion_trasado_cerecine',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cronograma_atencion',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cronograma_seguimiento',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='diagnostico_prenatal',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='equipo_anestesico_asignado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='hoja_contrarreferencia',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='info_maternidad',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='integracion_equipo_quirurgico',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='justificacion_traslado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='num_controles_embarazo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='prog_acciones',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='prog_acciones_caso_individual',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
