# Generated by Django 3.2.20 on 2023-09-13 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0007_auto_20230909_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='atresia_esofagica',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='atresia_estemos_intestinales',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='defectos_diafragmaticos',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='defectos_pared',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='otros',
        ),
        migrations.AddField(
            model_name='paciente',
            name='diagnostico_egreso',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='actuacion_segun_afeccion',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('np', 'Np'), ('empty', 'Empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellidos',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='captacion_precoz',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('empty', 'Empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='carnet_identidad_madre',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='clasificacion',
            field=models.CharField(blank=True, choices=[('d', 'D'), ('no d', 'NO D'), ('empty', 'Empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='coincidencia_diagnostica',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('empty', 'Empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='comprobacion_consejo_genetico',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('np', 'Np'), ('empty', 'Empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='confirmacion_segunda_opinion',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('empty', 'Empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='coordinacion_equipos_ginecologia',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('empty', 'Empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='coordinacion_trasado_cerecine',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('empty', 'Empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='coordinacion_traslado_provincial',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('np', 'Np'), ('empty', 'Empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 13, 16, 20, 10, 877157)),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='criterio_cirujano',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('np', 'Np'), ('empty', 'Empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cronograma_atencion',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('empty', 'Empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cronograma_seguimiento',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('empty', 'Empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='deficiencias_traslado',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='diagnostico_ingreso',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='diagnostico_prenatal',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('empty', 'Empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='documentos_contrarreferencia',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('empty', 'Empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='embarazada_de_riesgo',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('np', 'Np'), ('empty', 'Empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='equipo_anestesico_asignado',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('empty', 'Empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estudios_intervencion_quirurgica',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('np', 'Np'), ('empty', 'Empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='evaluacion_traslado',
            field=models.CharField(blank=True, choices=[('e', 'E'), ('mb', 'MB'), ('b', 'B'), ('at', 'AT'), ('empty', 'Empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ginecologo_asignado',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('np', 'Np'), ('empty', 'Empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='hoja_contrarreferencia',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('empty', 'Empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='info_maternidad',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('empty', 'Empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='integracion_equipo_quirurgico',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('empty', 'Empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='interconsulta_cirujano',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('np', 'Np'), ('empty', 'Empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='interconsulta_medica',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('np', 'Np'), ('empty', 'Empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='justificacion_traslado',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('empty', 'Empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='municipio',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='neonatologo_salon_parto',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('np', 'Np'), ('empty', 'Empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre_madre',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='num_controles_embarazo',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='prog_acciones',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('empty', 'Empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='prog_acciones_caso_individual',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('empty', 'Empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='provincia',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='resultado_alta',
            field=models.CharField(choices=[('vivo', 'Vivo'), ('muerto', 'Muerto'), ('empty', 'Empty')], default='empty', max_length=6),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
