# Generated by Django 3.2.20 on 2023-09-13 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0008_auto_20230913_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='deficiencias_traslado',
            new_name='deficiencias_trasl',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='nombre_madre',
            new_name='nombre_de_la_madre',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='num_controles_embarazo',
            new_name='numero_control',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='actuacion_segun_afeccion',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='captacion_precoz',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='coincidencia_diagnostica',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='comprobacion_consejo_genetico',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='confirmacion_segunda_opinion',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='coordinacion_equipos_ginecologia',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='coordinacion_trasado_cerecine',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='coordinacion_traslado_provincial',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='cronograma_seguimiento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='diagnostico_prenatal',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='documentos_contrarreferencia',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='embarazada_de_riesgo',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='equipo_anestesico_asignado',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='estudios_intervencion_quirurgica',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='evaluacion_traslado',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='ginecologo_asignado',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='hoja_contrarreferencia',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='integracion_equipo_quirurgico',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='interconsulta_cirujano',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='interconsulta_medica',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='justificacion_traslado',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='neonatologo_salon_parto',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='prog_acciones',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='prog_acciones_caso_individual',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='resultado_alta',
        ),
        migrations.AddField(
            model_name='paciente',
            name='accion_inmediatas',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('null', 'null')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='paciente',
            name='actuacion_afeccion',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('np', 'Np'), ('null', 'Null')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='paciente',
            name='alta',
            field=models.CharField(choices=[('vivo', 'Vivo'), ('muerto', 'Muerto'), ('null', 'null')], default='null', max_length=6),
        ),
        migrations.AddField(
            model_name='paciente',
            name='coincidencia_diag',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('null', 'null')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='paciente',
            name='confir_segunda_opinion',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('null', 'null')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='paciente',
            name='coordinacion_equipo',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('null', 'null')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='paciente',
            name='coordinacion_traslado1',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('np', 'Np'), ('null', 'Null')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='paciente',
            name='coordinacion_traslado2',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('null', 'null')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cronograma_seg',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('null', 'null')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='paciente',
            name='diag_prenatal',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('null', 'null')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='paciente',
            name='doc_contrarref',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('null', 'null')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='paciente',
            name='estudios_inter_quirurgica',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('np', 'Np'), ('null', 'Null')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='paciente',
            name='evaluacion_trasl',
            field=models.CharField(blank=True, choices=[('e', 'E'), ('mb', 'MB'), ('b', 'B'), ('at', 'AT'), ('null', 'null')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 13, 17, 11, 13, 984174)),
        ),
        migrations.AddField(
            model_name='paciente',
            name='genetico',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('np', 'Np'), ('null', 'Null')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ginecologo_asig',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('np', 'Np'), ('null', 'Null')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='paciente',
            name='hoja_conf',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('null', 'null')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='paciente',
            name='interconsult_cirujano',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('np', 'Np'), ('null', 'Null')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='paciente',
            name='interconsult_medica',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('np', 'Np'), ('null', 'Null')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='paciente',
            name='justific_traslado',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('null', 'null')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='paciente',
            name='precoz',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('null', 'null')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='paciente',
            name='presencia_en_salon',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('np', 'Np'), ('null', 'Null')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='paciente',
            name='programa_acciones',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('null', 'null')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='paciente',
            name='riesgo',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('np', 'Np'), ('null', 'Null')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='paciente',
            name='verificar_equipo_anestesico',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('null', 'null')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='paciente',
            name='verificar_equipo_quirurgico',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('null', 'null')], default='null', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='clasificacion',
            field=models.CharField(blank=True, choices=[('d', 'D'), ('no d', 'NO D'), ('null', 'null')], default='null', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='criterio_cirujano',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('np', 'Np'), ('null', 'Null')], default='null', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cronograma_atencion',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('null', 'null')], default='null', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='info_maternidad',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('null', 'null')], default='null', max_length=5),
        ),
    ]
