# Generated by Django 3.2.20 on 2023-09-13 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0009_auto_20230913_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='accion_inmediatas',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('empty', 'empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='actuacion_afeccion',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('np', 'Np'), ('empty', 'empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='alta',
            field=models.CharField(choices=[('vivo', 'Vivo'), ('muerto', 'Muerto'), ('empty', 'empty')], default='empty', max_length=6),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='clasificacion',
            field=models.CharField(blank=True, choices=[('d', 'D'), ('no d', 'NO D'), ('empty', 'empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='coincidencia_diag',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('empty', 'empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='confir_segunda_opinion',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('empty', 'empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='coordinacion_equipo',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('empty', 'empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='coordinacion_traslado1',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('np', 'Np'), ('empty', 'empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='coordinacion_traslado2',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('empty', 'empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='criterio_cirujano',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('np', 'Np'), ('empty', 'empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cronograma_atencion',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('empty', 'empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cronograma_seg',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('empty', 'empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='diag_prenatal',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('empty', 'empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='doc_contrarref',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('empty', 'empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estudios_inter_quirurgica',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('np', 'Np'), ('empty', 'empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='evaluacion_trasl',
            field=models.CharField(blank=True, choices=[('e', 'E'), ('mb', 'MB'), ('b', 'B'), ('at', 'AT'), ('empty', 'empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 13, 19, 3, 46, 949781)),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genetico',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('np', 'Np'), ('empty', 'empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ginecologo_asig',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('np', 'Np'), ('empty', 'empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='hoja_conf',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('empty', 'empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='info_maternidad',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('empty', 'empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='interconsult_cirujano',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('np', 'Np'), ('empty', 'empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='interconsult_medica',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('np', 'Np'), ('empty', 'empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='justific_traslado',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('empty', 'empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='precoz',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('empty', 'empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='presencia_en_salon',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('np', 'Np'), ('empty', 'empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='programa_acciones',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('empty', 'empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='riesgo',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('np', 'Np'), ('empty', 'empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='verificar_equipo_anestesico',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('empty', 'empty')], default='empty', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='verificar_equipo_quirurgico',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No'), ('empty', 'empty')], default='empty', max_length=5),
        ),
    ]
