# Generated by Django 3.2.20 on 2023-09-21 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0014_auto_20230915_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 21, 18, 30, 15, 975321)),
        ),
    ]
