# Generated by Django 3.2.20 on 2023-09-22 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0015_alter_paciente_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 11, 27, 51, 985604)),
        ),
    ]
