# Generated by Django 3.2.20 on 2023-09-22 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0017_alter_paciente_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 14, 1, 34, 616501)),
        ),
    ]
