# Generated by Django 3.2.20 on 2023-09-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0019_alter_paciente_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='evaluacion_atencion_medica',
            field=models.CharField(blank=True, default='Bien', max_length=15),
        ),
        migrations.AddField(
            model_name='paciente',
            name='evaluacion_atencion_primaria',
            field=models.CharField(blank=True, default='Bien', max_length=15),
        ),
        migrations.AddField(
            model_name='paciente',
            name='evaluacion_equipo_quirurgico',
            field=models.CharField(blank=True, default='Bien', max_length=15),
        ),
        migrations.AddField(
            model_name='paciente',
            name='evaluacion_hogar_materno',
            field=models.CharField(blank=True, default='Bien', max_length=15),
        ),
        migrations.AddField(
            model_name='paciente',
            name='evaluacion_regreso_neonato_operado',
            field=models.CharField(blank=True, default='Bien', max_length=15),
        ),
        migrations.AddField(
            model_name='paciente',
            name='evaluacion_servicio_neonatologia_cerecine',
            field=models.CharField(blank=True, default='Bien', max_length=15),
        ),
        migrations.AddField(
            model_name='paciente',
            name='evaluacion_servicio_neonatologia_provinciales',
            field=models.CharField(blank=True, default='Bien', max_length=15),
        ),
    ]
