# Generated by Django 3.2.20 on 2023-09-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0020_auto_20230923_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='evaluacion_atencion_medica',
            field=models.CharField(blank=True, default='B', max_length=15),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='evaluacion_atencion_primaria',
            field=models.CharField(blank=True, default='B', max_length=15),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='evaluacion_equipo_quirurgico',
            field=models.CharField(blank=True, default='B', max_length=15),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='evaluacion_hogar_materno',
            field=models.CharField(blank=True, default='B', max_length=15),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='evaluacion_regreso_neonato_operado',
            field=models.CharField(blank=True, default='B', max_length=15),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='evaluacion_servicio_neonatologia_cerecine',
            field=models.CharField(blank=True, default='B', max_length=15),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='evaluacion_servicio_neonatologia_provinciales',
            field=models.CharField(blank=True, default='B', max_length=15),
        ),
    ]
